json.video video,
           :id,
           :youtube_video_id,
           :title,
           :channel_title,
           :thumbnail_url,
           :duration,
           :description,
           :published,
           :current_time
